.TH CELLMOTUS 1 "JANUARY 2015" Linux "User Manuals"
.SH NAME
CellMotus \- Puzzle Game
.SH SYNOPSIS
.B Simple puzzle game. Tap cells to move them to the right color markers.
.SH DESCRIPTION
.PD 0
─────────────────────────▐█
.P
────▄──────────────────▄█▓█
.P
───▐██▄───────────────▄▓░░▓▓
.P
───▐█░██▓────────────▓▓░░░▓▌
.P
───▐█▌░▓██──────────█▓░░░░▓
.P
────▓█▌░░▓█▄███████▄███▓░▓█
.P
────▓██▌░▓██░░░░░░░░░░▓█░▓▌
.P
─────▓█████░░░░░░░░░░░░▓██
.P
─────▓██▓░░░░░░░░░░░░░░░▓█
.P
─────▐█▓░░░░░░█▓░░▓█░░░░▓█▌
.P
─────▓█▌░▓█▓▓██▓░█▓▓▓▓▓░▓█▌
.P
─────▓▓░▓██████▓░▓███▓▓▌░█▓
.P
────▐▓▓░█▄▐▓▌█▓░░▓█▐▓▌▄▓░██
.P
────▓█▓░▓█▄▄▄█▓░░▓█▄▄▄█▓░██▌
.P
────▓█▌░▓█████▓░░░▓███▓▀░▓█▓
.P
───▐▓█░░░▀▓██▀░░░░░─▀▓▀░░▓█▓
.P
───▓██░░░░░░░░▀▄▄▄▄▀░░░░░░▓▓
.P
───▓█▌░░░░░░░░░░▐▌░░░░░░░░▓▓▌
.P
───▓█░░░░░░░░░▄▀▀▀▀▄░░░░░░░█▓
.P
──▐█▌░░░░░░░░▀░░░░░░▀░░░░░░█▓
.P
──▓█░░░░░░░░░░░░░░░░░░░░░░░██▓
.P
──▓█░░░░░░░░░░░░░░░░░░░░░░░▓█▓
.P
──██░░░░░░░░░░░░░░░░░░░░░░░░█▓
.P
──█▌░░░░░░░░░░░░░░░░░░░░░░░░▐▓▌
.P
─▐▓░░░░░░░░░░░░░░░░░░░░░░░░░░█▓
.P
─█▓░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓
.P
─█▓░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓
.P
▐█▓░░░░░░░░░░░░░░░░░░░░░░░░░░░█
.P
█▓▌░░░░░░░░░░░░░░░░░░░░░░░░░░░▓
.PD 1
.SH FILES
.I ~/.CellMotus/.desktop
.RS
The system wide configuration file
.RE
.I ~/.CellMotus/.game
.RS
Game config
.RE
.I ~/usr/share/CellMotus/*
.RS
Game data
.SH AUTHOR
TimeFlask <TimeFlask at gmail dot com>
.SH "SEE ALSO"
Game about Squares
